
import { Category, Product, Ingredient, PizzaSize } from '../types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'PROMOS FLASH', icon: 'bolt', color: 'text-yellow-500' },
  { id: '2', name: 'PIZZAS TRADICIONALES', icon: 'pizza-slice', color: 'text-orange-500' },
  { id: '3', name: 'PIZZAS PREMIUM', icon: 'crown', color: 'text-purple-500' },
  { id: '4', name: 'PIZZAS DULCES', icon: 'cookie', color: 'text-pink-400' },
  { id: '5', name: 'ENTRADAS', icon: 'bread-slice', color: 'text-amber-500' },
  { id: '6', name: 'COMBOS', icon: 'box-open', color: 'text-green-500' },
  { id: '7', name: 'BEBIDAS', icon: 'wine-glass', color: 'text-cyan-500' },
  { id: '8', name: 'POSTRES', icon: 'ice-cream', color: 'text-pink-500' },
  { id: '9', name: 'SALSAS PARA MOJAR', icon: 'droplet', color: 'text-red-500' },
];

export const INGREDIENTS: Ingredient[] = [
  // BASES DE MASA (6)
  { id: 'base_1', nombre: 'Masa Artesanal', descripcion: '48h fermentación', precio_extra: 0, categoria: 'base', disponible: true, default: true },
  { id: 'base_2', nombre: 'Masa Integral', descripcion: 'Trigo entero', precio_extra: 3000, categoria: 'base', disponible: true },
  { id: 'base_3', nombre: 'Masa Sin Gluten', descripcion: 'Certificada', precio_extra: 5000, categoria: 'base', disponible: true },
  { id: 'base_4', nombre: 'Masa Delgada', descripcion: 'Extra crunch', precio_extra: 2000, categoria: 'base', disponible: true },
  { id: 'base_5', nombre: 'Masa Espesa', descripcion: 'Estilo Chicago', precio_extra: 2000, categoria: 'base', disponible: true },
  { id: 'base_6', nombre: 'Masa Focaccia', descripcion: 'Oliva y romero', precio_extra: 4000, categoria: 'base', disponible: true },

  // SALSAS (15)
  { id: 'salsa_1', nombre: 'Salsa Tomate Clásica', descripcion: 'San Marzano', precio_extra: 0, categoria: 'salsa', disponible: true, default: true },
  { id: 'salsa_2', nombre: 'Salsa César de la Casa', descripcion: 'Receta Guido', precio_extra: 4000, categoria: 'salsa', premium: true, disponible: true },
  { id: 'salsa_3', nombre: 'Salsa BBQ', descripcion: 'Ahumada', precio_extra: 2000, categoria: 'salsa', disponible: true },
  { id: 'salsa_4', nombre: 'Salsa Pesto', descripcion: 'Albahaca y piñones', precio_extra: 3000, categoria: 'salsa', disponible: true },
  { id: 'salsa_5', nombre: 'Salsa Blanca', descripcion: 'Crema premium', precio_extra: 2000, categoria: 'salsa', disponible: true },
  { id: 'salsa_6', nombre: 'Salsa Picante', descripcion: 'Habanero blend', precio_extra: 1000, categoria: 'salsa', disponible: true },
  { id: 'salsa_7', nombre: 'Salsa Alfredo', descripcion: 'Queso y crema', precio_extra: 3000, categoria: 'salsa', disponible: true },
  { id: 'salsa_8', nombre: 'Salsa Arrabbiata', descripcion: 'Picante suave', precio_extra: 2500, categoria: 'salsa', disponible: true },
  { id: 'salsa_9', nombre: 'Salsa Puttanesca', descripcion: 'Olivas y alcaparras', precio_extra: 3500, categoria: 'salsa', disponible: true },
  { id: 'salsa_10', nombre: 'Salsa Boloñesa', descripcion: 'Carne braseada', precio_extra: 3500, categoria: 'salsa', disponible: true },
  { id: 'salsa_11', nombre: 'Aceite de Oliva', descripcion: 'Extra virgen', precio_extra: 1000, categoria: 'salsa', disponible: true },
  { id: 'salsa_12', nombre: 'Sin Salsa', descripcion: 'Base blanca', precio_extra: 0, categoria: 'salsa', disponible: true },
  { id: 'salsa_13', nombre: 'Chocolate Fundido', descripcion: 'Especial dulce', precio_extra: 3000, categoria: 'salsa', disponible: true, dulce: true },
  { id: 'salsa_14', nombre: 'Nutella', descripcion: 'Avellana real', precio_extra: 4000, categoria: 'salsa', disponible: true, dulce: true },
  { id: 'salsa_15', nombre: 'Dulce de Leche', descripcion: 'Arequipe artesanal', precio_extra: 2500, categoria: 'salsa', disponible: true, dulce: true },

  // QUESOS (12)
  { id: 'queso_1', nombre: 'Mozzarella Tradicional', descripcion: 'Local fresco', precio_extra: 0, categoria: 'queso', disponible: true, default: true },
  { id: 'queso_2', nombre: 'Mozzarella de Búfala D.O.P.', descripcion: 'Importado', precio_extra: 8000, categoria: 'queso', premium: true, disponible: true },
  { id: 'queso_3', nombre: 'Parmesano Reggiano', descripcion: '24 meses', precio_extra: 5000, categoria: 'queso', premium: true, disponible: true },
  { id: 'queso_4', nombre: 'Queso Gouda', descripcion: 'Holandés suave', precio_extra: 3000, categoria: 'queso', disponible: true },
  { id: 'queso_5', nombre: 'Queso Crema', descripcion: 'Textura suave', precio_extra: 2000, categoria: 'queso', disponible: true },
  { id: 'queso_6', nombre: 'Queso Azul (Gorgonzola)', descripcion: 'Intenso', precio_extra: 6000, categoria: 'queso', disponible: true },
  { id: 'queso_7', nombre: 'Queso Vegano', descripcion: 'Base coco', precio_extra: 7000, categoria: 'queso', disponible: true, vegano: true },
  { id: 'queso_8', nombre: 'Doble Queso', descripcion: 'Extra mozzarella', precio_extra: 3000, categoria: 'queso', disponible: true },
  { id: 'queso_9', nombre: 'Queso Feta', descripcion: 'Griego auténtico', precio_extra: 4000, categoria: 'queso', disponible: true },
  { id: 'queso_10', nombre: 'Queso Provolone', descripcion: 'Ahumado', precio_extra: 3500, categoria: 'queso', disponible: true },
  { id: 'queso_11', nombre: 'Queso Fresco', descripcion: 'Campesino', precio_extra: 2500, categoria: 'queso', disponible: true },
  { id: 'queso_12', nombre: 'Queso Ricotta', descripcion: 'Cremoso', precio_extra: 4500, categoria: 'queso', disponible: true },

  // CARNES (18)
  { id: 'carne_1', nombre: 'Jamón Cocido Premium', precio_extra: 4000, categoria: 'carne', disponible: true, descripcion: 'Magro' },
  { id: 'carne_2', nombre: 'Pepperoni Importado', precio_extra: 5000, categoria: 'carne', disponible: true, descripcion: 'Spicy' },
  { id: 'carne_3', nombre: 'Salami Ibérico', precio_extra: 9000, categoria: 'carne', premium: true, disponible: true, descripcion: 'D.O.P' },
  { id: 'carne_4', nombre: 'Chorizo Español D.O.P.', precio_extra: 8000, categoria: 'carne', premium: true, disponible: true, descripcion: 'Ahumado' },
  { id: 'carne_5', nombre: 'Jamón Serrano 24 Meses', precio_extra: 10000, categoria: 'carne', premium: true, disponible: true, descripcion: 'Reserva' },
  { id: 'carne_6', nombre: 'Bresaola Curada 60 Días', precio_extra: 12000, categoria: 'carne', premium: true, disponible: true, descripcion: 'Corte magro' },
  { id: 'carne_7', nombre: 'Tocineta Ahumada', precio_extra: 5000, categoria: 'carne', disponible: true, descripcion: 'Crunchy' },
  { id: 'carne_8', nombre: 'Pollo BBQ', precio_extra: 6000, categoria: 'carne', disponible: true, descripcion: 'Pechuga' },
  { id: 'carne_9', nombre: 'Jamón de Pierna', precio_extra: 3000, categoria: 'carne', disponible: true, descripcion: 'Tradicional' },
  { id: 'carne_10', nombre: 'Prosciutto di Parma', precio_extra: 9500, categoria: 'carne', premium: true, disponible: true, descripcion: 'Italiano' },
  { id: 'carne_11', nombre: 'Salami Picante', precio_extra: 5500, categoria: 'carne', disponible: true, descripcion: 'Diavola' },
  { id: 'carne_12', nombre: 'Carne Molida Sazonada', precio_extra: 6000, categoria: 'carne', disponible: true, descripcion: 'Res' },
  { id: 'carne_13', nombre: 'Pollo Asado', precio_extra: 5500, categoria: 'carne', disponible: true, descripcion: 'Finas hierbas' },
  { id: 'carne_14', nombre: 'Salchicha Italiana', precio_extra: 5000, categoria: 'carne', disponible: true, descripcion: 'Hinojo' },
  { id: 'carne_15', nombre: 'Mortadela', precio_extra: 4000, categoria: 'carne', disponible: true, descripcion: 'Corte boloña' },
  { id: 'carne_16', nombre: 'Lomo de Cerdo', precio_extra: 7000, categoria: 'carne', disponible: true, descripcion: 'Asado' },
  { id: 'carne_17', nombre: 'Atún', precio_extra: 4500, categoria: 'carne', disponible: true, descripcion: 'Lomo' },
  { id: 'carne_18', nombre: 'Jamón de York', precio_extra: 3500, categoria: 'carne', disponible: true, descripcion: 'Clásico' },

  // VEGETALES (28)
  { id: 'veg_1', nombre: 'Tomate Fresco', precio_extra: 1000, categoria: 'vegetal', disponible: true, descripcion: 'En rodajas' },
  { id: 'veg_2', nombre: 'Piña Caramelizada', precio_extra: 2000, categoria: 'vegetal', disponible: true, descripcion: 'Asada' },
  { id: 'veg_3', nombre: 'Albahaca Fresca', precio_extra: 1000, categoria: 'vegetal', disponible: true, descripcion: 'Aromática' },
  { id: 'veg_4', nombre: 'Rúgula Fresca', precio_extra: 3000, categoria: 'vegetal', premium: true, disponible: true, descripcion: 'Silvestre' },
  { id: 'veg_5', nombre: 'Cebolla Morada', precio_extra: 1000, categoria: 'vegetal', disponible: true, descripcion: 'Pluma' },
  { id: 'veg_6', nombre: 'Cebolla Caramelizada', precio_extra: 3000, categoria: 'vegetal', premium: true, disponible: true, descripcion: 'Dulce' },
  { id: 'veg_7', nombre: 'Champiñones Frescos', precio_extra: 2000, categoria: 'vegetal', disponible: true, descripcion: 'Paris' },
  { id: 'veg_8', nombre: 'Pimientos de Colores', precio_extra: 2000, categoria: 'vegetal', disponible: true, descripcion: 'Trio' },
  { id: 'veg_9', nombre: 'Aceitunas Negras', descripcion: 'Aceitunas negras deshuesadas', precio_extra: 1000, categoria: 'vegetal', disponible: true },
  { id: 'veg_10', nombre: 'Aceitunas Verdes', descripcion: 'Aceitunas verdes rellenas', precio_extra: 1000, categoria: 'vegetal', disponible: true },
  { id: 'veg_11', nombre: 'Maíz Dulce', descripcion: 'Granos de maíz tierno', precio_extra: 1000, categoria: 'vegetal', disponible: true },
  { id: 'veg_12', nombre: 'Alcachofas', descripcion: 'Corazones de alcachofa en conserva', precio_extra: 4000, categoria: 'vegetal', disponible: true },
  { id: 'veg_13', nombre: 'Ajo Asado', descripcion: 'Dientes de ajo suavemente asados', precio_extra: 2000, categoria: 'vegetal', disponible: true },
  { id: 'veg_14', nombre: 'Aceite Trufado', descripcion: 'Aceite de oliva con aroma a trufa blanca', precio_extra: 7000, categoria: 'especia', premium: true, disponible: true },
  { id: 'veg_15', nombre: 'Orégano', descripcion: 'Orégano seco aromático', precio_extra: 500, categoria: 'especia', disponible: true, default: true },
  { id: 'veg_16', nombre: 'Sal de Ajo Colombiana', descripcion: 'Mezcla artesanal de sal y ajo', precio_extra: 1000, categoria: 'especia', disponible: true },
  { id: 'veg_17', nombre: 'Romero Fresco', descripcion: 'Hojas de romero recién cortadas', precio_extra: 2000, categoria: 'especia', disponible: true },
  { id: 'veg_18', nombre: 'Espinaca', descripcion: 'Hojas tiernas de espinaca fresca', precio_extra: 1500, categoria: 'vegetal', disponible: true },
  { id: 'veg_19', nombre: 'Berenjena', descripcion: 'Rodajas de berenjena asada', precio_extra: 2000, categoria: 'vegetal', disponible: true },
  { id: 'veg_20', nombre: 'Zanahoria', descripcion: 'Zanahoria fresca rallada', precio_extra: 1000, categoria: 'vegetal', disponible: true },
  { id: 'veg_21', nombre: 'Jalapeño', descripcion: 'Rodajas de jalapeño picante', precio_extra: 1500, categoria: 'vegetal', disponible: true },
  { id: 'veg_22', nombre: 'Pimiento Rojo', descripcion: 'Pimiento rojo dulce en tiras', precio_extra: 1500, categoria: 'vegetal', disponible: true },
  { id: 'veg_23', nombre: 'Aceitunas Kalamata', descripcion: 'Aceitunas griegas de sabor intenso', precio_extra: 2500, categoria: 'vegetal', premium: true, disponible: true },
  { id: 'veg_24', nombre: 'Tomate Cherry', descripcion: 'Tomates cherry dulces partidos a la mitad', precio_extra: 2000, categoria: 'vegetal', disponible: true },
  { id: 'veg_25', nombre: 'Berro', descripcion: 'Hojas frescas de berro silvestre', precio_extra: 2000, categoria: 'vegetal', disponible: true },
  { id: 'veg_26', nombre: 'Apio', descripcion: 'Apio fresco picado', precio_extra: 1000, categoria: 'vegetal', disponible: true },
  { id: 'veg_27', nombre: 'Cebollín', descripcion: 'Cebollín fresco finamente picado', precio_extra: 1000, categoria: 'vegetal', disponible: true },
  { id: 'veg_28', nombre: 'Perejil', descripcion: 'Perejil liso fresco', precio_extra: 500, categoria: 'vegetal', disponible: true },

  // DULCES (19)
  { id: 'dul_1', nombre: 'Fresas Frescas', descripcion: 'Fresas dulces de la sabana', precio_extra: 3000, categoria: 'dulce', disponible: true },
  { id: 'dul_2', nombre: 'Banano Fresco', descripcion: 'Rodajas de banano maduro', precio_extra: 2000, categoria: 'dulce', disponible: true },
  { id: 'dul_3', nombre: 'Nueces', descripcion: 'Nueces de nogal troceadas', precio_extra: 2500, categoria: 'dulce', disponible: true },
  { id: 'dul_4', nombre: 'Queso Fresco Dulce', descripcion: 'Queso campesino con toque dulce', precio_extra: 2500, categoria: 'dulce', disponible: true },
  { id: 'dul_5', nombre: 'Canela', descripcion: 'Canela en polvo de alta calidad', precio_extra: 1000, categoria: 'dulce', disponible: true },
  { id: 'dul_6', nombre: 'Coco Rallado', descripcion: 'Coco natural rallado y tostado', precio_extra: 2000, categoria: 'dulce', disponible: true },
  { id: 'dul_7', nombre: 'Pasas', descripcion: 'Uvas pasas sin semilla', precio_extra: 1500, categoria: 'dulce', disponible: true },
  { id: 'dul_8', nombre: 'Manjar Blanco', descripcion: 'Postre tradicional de leche', precio_extra: 2500, categoria: 'dulce', disponible: true },
  { id: 'dul_9', nombre: 'Tres Leches', descripcion: 'Mezcla cremosa de tres leches', precio_extra: 3000, categoria: 'dulce', disponible: true },
  { id: 'dul_10', nombre: 'Arequipe', descripcion: 'Dulce de leche artesanal', precio_extra: 2500, categoria: 'dulce', disponible: true },
  { id: 'dul_11', nombre: 'Azúcar Glass', descripcion: 'Azúcar pulverizada fina', precio_extra: 1000, categoria: 'dulce', disponible: true },
  { id: 'dul_12', nombre: 'Mantequilla Dulce', descripcion: 'Mantequilla cremosa con azúcar', precio_extra: 1500, categoria: 'dulce', disponible: true },
  { id: 'dul_13', nombre: 'Galletas Oreo', descripcion: 'Trozos crujientes de galleta Oreo', precio_extra: 3000, categoria: 'dulce', disponible: true },
  { id: 'dul_14', nombre: 'Chocolate Blanco', descripcion: 'Chispas de chocolate blanco premium', precio_extra: 2500, categoria: 'dulce', disponible: true },
  { id: 'dul_15', nombre: 'Mango Fresco', descripcion: 'Cubos de mango dulce', precio_extra: 2500, categoria: 'dulce', disponible: true },
  { id: 'dul_16', nombre: 'Piña Fresca', descripcion: 'Trozos de piña natural', precio_extra: 2000, categoria: 'dulce', disponible: true },
  { id: 'dul_17', nombre: 'Miel', descripcion: 'Miel de abejas pura', precio_extra: 1500, categoria: 'dulce', disponible: true },
  { id: 'dul_18', nombre: 'Merengue', descripcion: 'Trozos de merengue crujiente', precio_extra: 2000, categoria: 'dulce', disponible: true },
  { id: 'dul_19', nombre: 'Azúcar Morena', descripcion: 'Azúcar morena orgánica', precio_extra: 1000, categoria: 'dulce', disponible: true },

  // EXTRAS ESPECIALES (13)
  { id: 'ext_1', nombre: 'Huevo Frito', descripcion: 'Huevo frito en el momento', precio_extra: 3000, categoria: 'extra', disponible: true },
  { id: 'ext_2', nombre: 'Tocineta Extra', descripcion: 'Porción adicional de tocineta', precio_extra: 4000, categoria: 'extra', disponible: true },
  { id: 'ext_3', nombre: 'Pepperoni Extra', descripcion: 'Porción adicional de pepperoni', precio_extra: 4000, categoria: 'extra', disponible: true },
  { id: 'ext_4', nombre: 'Queso Extra', descripcion: 'Porción adicional de mozzarella', precio_extra: 5000, categoria: 'extra', disponible: true },
  { id: 'ext_5', nombre: 'Jamón Extra', descripcion: 'Porción adicional de jamón', precio_extra: 3500, categoria: 'extra', disponible: true },
  { id: 'ext_6', nombre: 'Champiñones Extra', descripcion: 'Porción adicional de champiñones', precio_extra: 2500, categoria: 'extra', disponible: true },
  { id: 'ext_7', nombre: 'Piña Extra', descripcion: 'Porción adicional de piña', precio_extra: 2000, categoria: 'extra', disponible: true },
  { id: 'ext_8', nombre: 'Aceitunas Extra', descripcion: 'Porción adicional de aceitunas', precio_extra: 1500, categoria: 'extra', disponible: true },
  { id: 'ext_9', nombre: 'Cebolla Extra', descripcion: 'Porción adicional de cebolla', precio_extra: 1500, categoria: 'extra', disponible: true },
  { id: 'ext_10', nombre: 'Orégano Extra', descripcion: 'Porción adicional de orégano', precio_extra: 500, categoria: 'extra', disponible: true },
  { id: 'ext_11', nombre: 'Aceite de Oliva Extra', descripcion: 'Chorro adicional de aceite de oliva', precio_extra: 1500, categoria: 'extra', disponible: true },
  { id: 'ext_12', nombre: 'Parmesano Extra', descripcion: 'Porción adicional de parmesano', precio_extra: 3000, categoria: 'extra', disponible: true },
  { id: 'ext_13', nombre: 'Rúgula Extra', descripcion: 'Porción adicional de rúgula fresca', precio_extra: 2500, categoria: 'extra', disponible: true },
];

export const PRODUCTS: Product[] = [
  // --- PIZZAS TRADICIONALES (12) ---
  { id: 'p_trad_1', categoryId: '2', nombre: 'Jamón y Queso', descripcion: 'Clásica con jamón cocido premium y mozzarella doble', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591', tiempo: 15, calorias: 280, popularidad: 95 },
  { id: 'p_trad_2', categoryId: '2', nombre: 'Hawaiana', descripcion: 'Piña caramelizada y jamón premium magro', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38', tiempo: 15, calorias: 265, popularidad: 88 },
  { id: 'p_trad_3', categoryId: '2', nombre: 'Napolitana', descripcion: 'Tomate fresco, albahaca italiana y ajo asado', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad38', tiempo: 15, vegetariano: true },
  { id: 'p_trad_4', categoryId: '2', nombre: 'Margarita', descripcion: 'Mozzarella D.O.P y sal de ajo colombiana', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad38', tiempo: 15, vegetariano: true },
  { id: 'p_trad_5', categoryId: '2', nombre: 'Vegetariana', descripcion: 'Explosión de vegetales frescos de la sabana', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591', vegetariano: true },
  { id: 'p_trad_6', categoryId: '2', nombre: 'Pepperoni', descripcion: 'Pepperoni importado curado y mozzarella', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e' },
  { id: 'p_trad_7', categoryId: '2', nombre: 'Tocineta y Champiñón', descripcion: 'Tocineta ahumada con champiñones Paris', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'p_trad_8', categoryId: '2', nombre: 'Cuatro Quesos', descripcion: 'Mozzarella, parmesano, gouda y crema', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'p_trad_9', categoryId: '2', nombre: 'Barbacoa', descripcion: 'Pollo desmechado y salsa BBQ ahumada', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'p_trad_10', categoryId: '2', nombre: 'Mexicana', descripcion: 'Jalapeños, carne molida y maíz tierno', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'p_trad_11', categoryId: '2', nombre: 'Aceitunas', descripcion: 'Mix de aceitunas con orégano y ajo', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'p_trad_12', categoryId: '2', nombre: 'Especial Suba', descripcion: 'Ícono local: jamón, piña, tocineta y champiñón', basePrice: 23900, type: 'tradicional', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591', exclusiva: true },

  // --- PIZZAS PREMIUM (12) ---
  { id: 'p_prem_1', categoryId: '3', nombre: 'ESPAÑOLA', descripcion: 'Salami ibérico y chorizo español D.O.P.', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1593504049359-74330189a345', isPremium: true, origen: 'España' },
  { id: 'p_prem_2', categoryId: '3', nombre: 'LA RÚSTICA', descripcion: 'Cebolla caramelizada y romero fresco de huerta', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591', isPremium: true },
  { id: 'p_prem_3', categoryId: '3', nombre: 'LA GUIDO', descripcion: 'Salsa César, rúgula silvestre y aceite trufado', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1539252554452-da30fa5d24c6', isPremium: true },
  { id: 'p_prem_4', categoryId: '3', nombre: 'GUIDO PIZZA', descripcion: 'Parmesano reggiano y trufa blanca italiana', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1539252554452-da30fa5d24c6', isPremium: true },
  { id: 'p_prem_5', categoryId: '3', nombre: 'BRESAOLA', descripcion: 'Bresaola curada 60 días y parmesano 24M', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1593504049359-74330189a345', isPremium: true },
  { id: 'p_prem_6', categoryId: '3', nombre: 'GENOVA', descripcion: 'Pesto genovés artesanal y búfala D.O.P.', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1574071318508-1cdbad80ad38', isPremium: true },
  { id: 'p_prem_7', categoryId: '3', nombre: 'CAPRICCIOSA', descripcion: 'Corazones de alcachofa, jamón y olivas', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591', isPremium: true },
  { id: 'p_prem_8', categoryId: '3', nombre: 'PROSCIUTTO', descripcion: 'Prosciutto di Parma y rúgula fresca', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1593504049359-74330189a345', isPremium: true },
  { id: 'p_prem_9', categoryId: '3', nombre: 'TRUFADA', descripcion: 'Aceite de trufa y champiñones silvestres', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1539252554452-da30fa5d24c6', isPremium: true },
  { id: 'p_prem_10', categoryId: '3', nombre: 'MEDITERRÁNEA', descripcion: 'Aceitunas kalamata y queso feta griego', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591', isPremium: true },
  { id: 'p_prem_11', categoryId: '3', nombre: 'DIAVOLA', descripcion: 'Salami picante, jalapeños y chili flakes', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e', isPremium: true },
  { id: 'p_prem_12', categoryId: '3', nombre: 'GOURMET SUBA', descripcion: 'Serrano 24M, rúgula y reducción balsámica', basePrice: 28900, type: 'premium', image: 'https://images.unsplash.com/photo-1593504049359-74330189a345', isPremium: true },

  // --- PIZZAS DULCES (8) ---
  { id: 'p_sweet_1', categoryId: '4', nombre: 'Chocolate y Fresa', descripcion: 'Nutella, fresas frescas y queso crema', basePrice: 26900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_2', categoryId: '4', nombre: 'Nutella Banano', descripcion: 'Crema de avellanas, banano y nueces', basePrice: 27900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_3', categoryId: '4', nombre: 'Dulce de Leche', descripcion: 'Arequipe artesanal y coco tostado', basePrice: 25900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_4', categoryId: '4', nombre: 'Manjar Blanco', descripcion: 'Tradición colombiana y uvas pasas', basePrice: 24900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_5', categoryId: '4', nombre: 'Tres Leches', descripcion: 'Base cremosa, merengue y arequipe', basePrice: 28900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_6', categoryId: '4', nombre: 'Canela Azúcar', descripcion: 'Base clásica, mantequilla y canela', basePrice: 22900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_7', categoryId: '4', nombre: 'Oreo Cream', descripcion: 'Galletas Oreo y crema chantilly', basePrice: 27900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },
  { id: 'p_sweet_8', categoryId: '4', nombre: 'Tropical Sweet', descripcion: 'Mango fresco, piña y miel orgánica', basePrice: 26900, type: 'dulce', image: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845' },

  // --- ENTRADAS (10) ---
  { id: 'e_1', categoryId: '5', nombre: 'Palitos de Queso', descripcion: 'Masa de la casa rellena de mozzarella', basePrice: 12900, type: 'entrada', porcion: '6 unidades', image: 'https://images.unsplash.com/photo-1548340748-6d2b7d7c1768', vegetariano: true },
  { id: 'e_2', categoryId: '5', nombre: 'Pan de Ajo', descripcion: 'Pan artesanal con mantequilla de ajo', basePrice: 9900, type: 'entrada', porcion: '4 unidades', image: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c', vegetariano: true },
  { id: 'e_3', categoryId: '5', nombre: 'Alitas Buffalo', descripcion: 'Alitas picantes con salsa original', basePrice: 18900, type: 'entrada', porcion: '10 unidades', image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f' },
  { id: 'e_4', categoryId: '5', nombre: 'Alitas BBQ', descripcion: 'Alitas glaseadas en salsa BBQ', basePrice: 18900, type: 'entrada', porcion: '10 unidades', image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f' },
  { id: 'e_5', categoryId: '5', nombre: 'Ensalada César', descripcion: 'Romana, crutones y parmesano reggiano', basePrice: 16900, type: 'entrada', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c' },
  { id: 'e_6', categoryId: '5', nombre: 'Ensalada Vegetariana', descripcion: 'Mix de hojas verdes y vegetales frescos', basePrice: 14900, type: 'entrada', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c', vegetariano: true },
  { id: 'e_7', categoryId: '5', nombre: 'Nuggets con Queso', descripcion: 'Pollo crujiente con dip de queso', basePrice: 15900, type: 'entrada', porcion: '8 unidades', image: 'https://images.unsplash.com/photo-1562967914-6c82c3f8a47c' },
  { id: 'e_8', categoryId: '5', nombre: 'Papas Fritas', descripcion: 'Corte tradicional crujiente', basePrice: 8900, type: 'entrada', porcion: 'Mediana', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877', vegetariano: true },
  { id: 'e_9', categoryId: '5', nombre: 'Papas con Queso', descripcion: 'Papas fritas con cheddar fundido', basePrice: 11900, type: 'entrada', porcion: 'Mediana', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877', vegetariano: true },
  { id: 'e_10', categoryId: '5', nombre: 'Bruschetta', descripcion: 'Tomate, albahaca y oliva sobre pan tostado', basePrice: 13900, type: 'entrada', porcion: '4 unidades', image: 'https://images.unsplash.com/photo-1572656631137-7935297eff55', vegetariano: true },

  // --- COMBOS (12) ---
  { id: 'c_1', categoryId: '6', nombre: 'Combo Suprema', descripcion: 'Pizza Suprema Mediana + Bebida 1L', basePrice: 32900, ahorro: 6300, descuento: '16%', personas: 1, type: 'combo', contenido: ['Pizza Suprema', 'Bebida 1L'], image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_2', categoryId: '6', nombre: 'Combo 2x1 Personal', descripcion: '2 Pizzas Personales + Bebida 1L', basePrice: 36900, ahorro: 5500, descuento: '13%', personas: 2, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_3', categoryId: '6', nombre: 'Combo Familiar 3+', descripcion: '3 Pizzas Personales + Bebida 1L', basePrice: 73900, ahorro: 12500, descuento: '14%', personas: 3, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_4', categoryId: '6', nombre: 'Combo 2 Tradicionales', descripcion: '2 Pizzas Medianas Tradicionales', basePrice: 39800, ahorro: 8000, descuento: '17%', personas: 2, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_5', categoryId: '6', nombre: 'Combo Pareja Premium', descripcion: '2 Premium Medianas + 2 Bebidas 500ml', basePrice: 69900, ahorro: 10000, descuento: '13%', personas: 2, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_6', categoryId: '6', nombre: 'Combo Familiar Grande', descripcion: '1 Pizza Grande + Entrada + Bebida 1.5L', basePrice: 64900, ahorro: 8000, descuento: '11%', personas: 4, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_7', categoryId: '6', nombre: 'Combo Individual Plus', descripcion: '1 Pizza Personal + Bebida 500ml', basePrice: 22900, ahorro: 3500, descuento: '13%', personas: 1, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_8', categoryId: '6', nombre: 'Combo Jamón y Queso', descripcion: 'Personal Jamón/Queso + Bebida 500ml', basePrice: 21900, ahorro: 2000, descuento: '8%', personas: 1, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_9', categoryId: '6', nombre: 'Combo Mitad Familiar', descripcion: 'Grande Mitad/Mitad + 2 Bebidas 1L + Entrada', basePrice: 89900, ahorro: 15000, descuento: '14%', personas: 4, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_10', categoryId: '6', nombre: 'Combo Romántico', descripcion: 'Premium Mediana + Entrada + Postre + Bebida', basePrice: 59900, ahorro: 8000, descuento: '12%', personas: 2, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_11', categoryId: '6', nombre: 'Combo Fiesta', descripcion: '2 Grandes + 2 Entradas + 2L Bebida + Postre', basePrice: 119900, ahorro: 20000, descuento: '14%', personas: 6, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },
  { id: 'c_12', categoryId: '6', nombre: 'Combo Ejecutivo', descripcion: 'Pizza Personal + Café + Galleta', basePrice: 24900, ahorro: 3000, descuento: '11%', personas: 1, type: 'combo', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591' },

  // --- BEBIDAS (20) ---
  { id: 'b_1', categoryId: '7', nombre: 'Coca-Cola 1.0L', descripcion: 'Refrescante bebida gaseosa original', basePrice: 6500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_2', categoryId: '7', nombre: 'Postobón 1.0L', descripcion: 'Gaseosa colombiana de diversos sabores', basePrice: 6500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_3', categoryId: '7', nombre: 'Sprite 1.0L', descripcion: 'Bebida gaseosa sabor lima-limón', basePrice: 6500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_4', categoryId: '7', nombre: 'Colombiana 1.0L', descripcion: 'La gaseosa nacional con sabor único', basePrice: 6500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_5', categoryId: '7', nombre: 'Jugo de Naranja Natural', descripcion: 'Zumo de naranja recién exprimido', basePrice: 8000, type: 'bebida', image: 'https://images.unsplash.com/photo-1557800636-894a64c1696f' },
  { id: 'b_6', categoryId: '7', nombre: 'Limonada Natural', descripcion: 'Refrescante jugo de limón con azúcar', basePrice: 7000, type: 'bebida', image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38' },
  { id: 'b_7', categoryId: '7', nombre: 'Club Colombia', descripcion: 'Cerveza premium colombiana', basePrice: 8000, type: 'bebida', image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13' },
  { id: 'b_8', categoryId: '7', nombre: 'Hatsu Té Blanco', descripcion: 'Té premium sabor granada', basePrice: 9500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_9', categoryId: '7', nombre: 'Agua Manantial con Gas', descripcion: 'Agua mineral de fuente natural', basePrice: 5500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_10', categoryId: '7', nombre: 'Agua Manantial Sin Gas', descripcion: 'Agua mineral pura', basePrice: 5000, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_11', categoryId: '7', nombre: 'Gatorade Blue', descripcion: 'Bebida hidratante para deportistas', basePrice: 7500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_12', categoryId: '7', nombre: 'Heineken 330ml', descripcion: 'Cerveza importada premium', basePrice: 9000, type: 'bebida', image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13' },
  { id: 'b_13', categoryId: '7', nombre: 'Stella Artois', descripcion: 'Cerveza belga de alta calidad', basePrice: 9500, type: 'bebida', image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13' },
  { id: 'b_14', categoryId: '7', nombre: 'Quatro 1.5L', descripcion: 'Gaseosa sabor pomelo toronja', basePrice: 8000, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_15', categoryId: '7', nombre: 'Coca-Cola Sin Azúcar 1L', descripcion: 'Sabor original sin calorías', basePrice: 6500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_16', categoryId: '7', nombre: 'Cerveza Corona', descripcion: 'Cerveza mexicana con limón', basePrice: 8500, type: 'bebida', image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13' },
  { id: 'b_17', categoryId: '7', nombre: 'Jugo del Valle Mango', descripcion: 'Néctar de fruta natural', basePrice: 6000, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_18', categoryId: '7', nombre: 'Fuze Tea Limón', descripcion: 'Té helado refrescante', basePrice: 7000, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_19', categoryId: '7', nombre: 'Ginger Ale 1L', descripcion: 'Bebida gaseosa sabor jengibre', basePrice: 7500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },
  { id: 'b_20', categoryId: '7', nombre: 'Soda Bretaña', descripcion: 'Agua con gas para mezclar', basePrice: 5500, type: 'bebida', image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97' },

  // --- POSTRES (10) ---
  { id: 'po_1', categoryId: '8', nombre: 'Brownie Artesanal', descripcion: 'Casero con nueces y chispas', basePrice: 12900, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1564355808539-22fda35bcd7e' },
  { id: 'po_2', categoryId: '8', nombre: 'Alfajor Triple', descripcion: 'Relleno de arequipe colombiano', basePrice: 8900, type: 'postre', porcion: '3 unidades', image: 'https://images.unsplash.com/photo-1590080876351-941da3576dee' },
  { id: 'po_3', categoryId: '8', nombre: 'Tiramisú', descripcion: 'Café premium y mascarpone', basePrice: 14900, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9' },
  { id: 'po_4', categoryId: '8', nombre: 'Cheesecake', descripcion: 'New York style con frutos rojos', basePrice: 15900, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad' },
  { id: 'po_5', categoryId: '8', nombre: 'Torta Tres Leches', descripcion: 'Crema y merengue suave', basePrice: 11900, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1543508282-5c1f427f023f' },
  { id: 'po_6', categoryId: '8', nombre: 'Mousse de Maracuyá', descripcion: 'Ligero y ácido con fruta real', basePrice: 9900, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1564355808539-22fda35bcd7e' },
  { id: 'po_7', categoryId: '8', nombre: 'Flan de Caramelo', descripcion: 'Receta clásica de la abuela', basePrice: 8500, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1564355808539-22fda35bcd7e' },
  { id: 'po_8', categoryId: '8', nombre: 'Canelazos Sweet', descripcion: 'Masitas de canela con dip de arequipe', basePrice: 13500, type: 'postre', porcion: 'Para compartir', image: 'https://images.unsplash.com/photo-1564355808539-22fda35bcd7e' },
  { id: 'po_9', categoryId: '8', nombre: 'Galletón con Helado', descripcion: 'Galleta caliente con vainilla premium', basePrice: 16900, type: 'postre', porcion: 'Individual', image: 'https://images.unsplash.com/photo-1564355808539-22fda35bcd7e' },
  { id: 'po_10', categoryId: '8', nombre: 'Profiteroles', descripcion: 'Rellenos de crema y bañados en chocolate', basePrice: 14500, type: 'postre', porcion: '3 unidades', image: 'https://images.unsplash.com/photo-1564355808539-22fda35bcd7e' },

  // --- SALSAS PARA MOJAR (15) ---
  { id: 's_1', categoryId: '9', nombre: 'Salsa Ranch', descripcion: 'Cremosa salsa ranchera artesanal', basePrice: 2000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_2', categoryId: '9', nombre: 'Salsa BBQ Mojada', descripcion: 'Salsa barbacoa ahumada para dipear', basePrice: 2000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_3', categoryId: '9', nombre: 'Salsa de Ajo', descripcion: 'Intensa salsa de ajo de la casa', basePrice: 2000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_4', categoryId: '9', nombre: 'Salsa César Dip', descripcion: 'La famosa receta César en versión dip', basePrice: 3000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_5', categoryId: '9', nombre: 'Aceite Balsámico', descripcion: 'Reducción de vinagre balsámico y oliva', basePrice: 2500, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_6', categoryId: '9', nombre: 'Miel Mostaza', descripcion: 'Equilibrio dulce y picante', basePrice: 2000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_7', categoryId: '9', nombre: 'Salsa Búfalo Hot', descripcion: 'Picante extremo original', basePrice: 3000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_8', categoryId: '9', nombre: 'Dip Queso Azul', descripcion: 'Gorgonzola cremoso premium', basePrice: 4500, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_9', categoryId: '9', nombre: 'Pesto Mayo', descripcion: 'Mayonesa artesanal con pesto fresco', basePrice: 3500, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_10', categoryId: '9', nombre: 'Sweet Chili', descripcion: 'Salsa agridulce con trozos de chili', basePrice: 2500, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_11', categoryId: '9', nombre: 'Salsa Tártara', descripcion: 'Con alcaparras y pepinillos', basePrice: 2000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_12', categoryId: '9', nombre: 'Dip Cheddar', descripcion: 'Queso cheddar fundido caliente', basePrice: 4000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_13', categoryId: '9', nombre: 'Chimichurri', descripcion: 'Receta de la casa con hierbas frescas', basePrice: 2500, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_14', categoryId: '9', nombre: 'Alioli de Trufa', descripcion: 'Mayonesa de ajo con aceite trufado', basePrice: 5000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
  { id: 's_15', categoryId: '9', nombre: 'Salsa Chipotle', descripcion: 'Ahumada y picante suave', basePrice: 3000, type: 'salsa_mojada', image: 'https://images.unsplash.com/photo-1563599175592-c58dc214deff' },
];

export const SIZE_FACTORS = {
  [PizzaSize.PERSONAL]: 1.0,
  [PizzaSize.MEDIANA]: 1.52,
  [PizzaSize.GRANDE]: 1.80
};
