// Carta real de Juancho's Pizza -- fuente de verdad única para el sitio
// público (MenuDigital.tsx, index.html) y la CRM (MenuInteligente.tsx),
// ambos leen /api/products, /api/categories, /api/ingredients y
// /api/pizza-sizes en vez de tener datos hardcodeados por separado.
//
// Usado por POST /api/seed (server/routes/misc.js). Todos los ids son
// deterministas para que re-sembrar sea un upsert idempotente, no una
// duplicación.

const COMBINING_DIACRITICS = new RegExp(
  '[' + String.fromCharCode(0x0300) + '-' + String.fromCharCode(0x036f) + ']',
  'g'
);

function slug(nombre) {
  return nombre
    .toLowerCase()
    .normalize('NFD')
    .replace(COMBINING_DIACRITICS, '') // strip accents (NFD decomposes é -> e + combining mark)
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export const CATEGORIES = [
  { id: 'pizzas', name: 'Pizza', icon: 'pizza-slice', color: 'text-orange-500' },
  { id: 'hamburguesas', name: 'Hamburguesas', icon: 'burger', color: 'text-amber-600' },
  { id: 'pastas', name: 'Lasagnas & Spaghettis', icon: 'bowl-food', color: 'text-yellow-600' },
  { id: 'calientes', name: 'Salchipapas & Perros calientes', icon: 'hotdog', color: 'text-red-500' },
  { id: 'especiales', name: 'Especiales', icon: 'star', color: 'text-purple-500' },
  { id: 'adicionales', name: 'Adicionales', icon: 'plus', color: 'text-stone-500' },
  { id: 'bebidas', name: 'Bebidas', icon: 'wine-glass', color: 'text-cyan-500' },
];

const IMG = {
  pizzaHawaiana: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
  pizzaPollo: 'https://images.unsplash.com/photo-1555109307-f7d9da25c244?auto=format&fit=crop&w=600&q=80',
  pizzaCarnes: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80',
  pizzaCostillitas: 'https://images.unsplash.com/photo-1566853923569-3c0eb2e79edf?auto=format&fit=crop&w=600&q=80',
  pizzaCriolla: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=600&q=80',
  pizzaMexicana: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=600&q=80',
  pizzaRanchera: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
  pizzaDeLaCasa: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=600&q=80',
  pizzaEspanola: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=600&q=80',
  pizzaNapolitana: 'https://images.unsplash.com/photo-1588315029754-2dd089d39a07?auto=format&fit=crop&w=600&q=80',
  pizzaVegetariana: 'https://images.unsplash.com/photo-1604917877934-07d8d248d396?auto=format&fit=crop&w=600&q=80',
  pizzaTropical: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=600&q=80',
  pizzaQuesoBocadillo: 'https://images.unsplash.com/photo-1512152272829-e3139592d56f?auto=format&fit=crop&w=600&q=80',
  pizzaSlice: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80',
  hamburguesa1: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
  hamburguesa2: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80',
  hamburguesa3: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
  pasta: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?auto=format&fit=crop&w=600&q=80',
  salchipapa: 'https://images.unsplash.com/photo-1624378420232-d5f1341b5c37?auto=format&fit=crop&w=600&q=80',
  perro: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?auto=format&fit=crop&w=600&q=80',
  mazorcada: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
  pechuga: 'https://images.unsplash.com/photo-1608039829572-9e18f2cf88d2?auto=format&fit=crop&w=600&q=80',
  churrasco: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
  bebida: 'https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?auto=format&fit=crop&w=600&q=80',
};

// { id, categoryId, subcategory, nombre, descripcion, basePrice, type, image,
//   vegetariano, comboPrice? } -- comboPrice se traduce a una menu_variant
// "Combo" (delta) en el seed, no es columna real de products.
export const PRODUCTS = [
  // ── Pizza (13 sabores fijos, precio = tamaño Small; el resto de tamaños
  //    sale de pizza_sizes) ──────────────────────────────────────────
  {
    id: 'pz-hawaiana',
    categoryId: 'pizzas',
    nombre: 'Hawaiana',
    descripcion: 'Piña, Jamón',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaHawaiana,
  },
  {
    id: 'pz-pollo-champinones',
    categoryId: 'pizzas',
    nombre: 'Pollo y champiñones',
    descripcion: 'Jamón, Champiñones, Pollo desmechado',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaPollo,
  },
  {
    id: 'pz-carnes',
    categoryId: 'pizzas',
    nombre: 'Carnes',
    descripcion: 'Jamón, Salami, Cabano',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaCarnes,
  },
  {
    id: 'pz-costillitas-bbq',
    categoryId: 'pizzas',
    nombre: 'Costillitas BBQ',
    descripcion: 'Jamón, Costillas BBQ, Maíz tierno',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaCostillitas,
  },
  {
    id: 'pz-criolla',
    categoryId: 'pizzas',
    nombre: 'Criolla',
    descripcion: 'Carne desmechada, Maíz tierno',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaCriolla,
  },
  {
    id: 'pz-mexicana',
    categoryId: 'pizzas',
    nombre: 'Mexicana',
    descripcion: 'Carne molida, Maíz tierno, Tomate, Cilantro, Tostacos',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaMexicana,
  },
  {
    id: 'pz-ranchera',
    categoryId: 'pizzas',
    nombre: 'Ranchera',
    descripcion: 'Champiñones, Cebolla, Maíz tierno, Chorizo',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaRanchera,
  },
  {
    id: 'pz-de-la-casa',
    categoryId: 'pizzas',
    nombre: 'De la casa',
    descripcion: 'Champiñones, Cebolla, Carne desmechada',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaDeLaCasa,
  },
  {
    id: 'pz-espanola',
    categoryId: 'pizzas',
    nombre: 'Española',
    descripcion: 'Espinaca, Tocineta, Maíz tierno, Champiñón',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaEspanola,
  },
  {
    id: 'pz-napolitana',
    categoryId: 'pizzas',
    nombre: 'Napolitana',
    descripcion: 'Tomate, Orégano',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaNapolitana,
  },
  {
    id: 'pz-vegetariana',
    categoryId: 'pizzas',
    nombre: 'Vegetariana',
    descripcion: 'Champiñón, Maíz tierno, Cebolla',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaVegetariana,
    vegetariano: true,
  },
  {
    id: 'pz-tropical',
    categoryId: 'pizzas',
    nombre: 'Tropical',
    descripcion: 'Cerezas, Piña, Duraznos, Uvas pasas',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaTropical,
    vegetariano: true,
  },
  {
    id: 'pz-queso-bocadillo',
    categoryId: 'pizzas',
    nombre: 'Queso y bocadillo',
    descripcion: 'Queso y bocadillo',
    basePrice: 30000,
    type: 'tradicional',
    image: IMG.pizzaQuesoBocadillo,
    vegetariano: true,
  },
  {
    id: 'pz-porcion',
    categoryId: 'pizzas',
    subcategory: 'Porción',
    nombre: 'Porción individual',
    descripcion: 'Porción individual de pizza',
    basePrice: 9200,
    type: 'tradicional',
    image: IMG.pizzaSlice,
  },

  // ── Hamburguesas (3 tiers) ───────────────────────────────────────
  {
    id: 'ham-plancha-sencilla',
    categoryId: 'hamburguesas',
    subcategory: 'A la plancha',
    nombre: 'Hamburguesa sencilla',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan',
    basePrice: 17500,
    comboPrice: 25500,
    type: 'tradicional',
    image: IMG.hamburguesa2,
  },
  {
    id: 'ham-plancha-especial',
    categoryId: 'hamburguesas',
    subcategory: 'A la plancha',
    nombre: 'Hamburguesa especial',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, champiñones, pollo, salsas showy',
    basePrice: 18000,
    comboPrice: 26500,
    type: 'tradicional',
    image: IMG.hamburguesa1,
  },
  {
    id: 'ham-plancha-sencilla-doble',
    categoryId: 'hamburguesas',
    subcategory: 'A la plancha',
    nombre: 'Sencilla doble carne',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, champiñones, pollo, salsas showy',
    basePrice: 21500,
    comboPrice: 28000,
    type: 'tradicional',
    image: IMG.hamburguesa2,
  },
  {
    id: 'ham-plancha-especial-doble',
    categoryId: 'hamburguesas',
    subcategory: 'A la plancha',
    nombre: 'Especial doble carne',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, champiñones, pollo, salsas showy',
    basePrice: 22000,
    comboPrice: 29000,
    type: 'tradicional',
    image: IMG.hamburguesa1,
  },
  {
    id: 'ham-apanada-sencilla',
    categoryId: 'hamburguesas',
    subcategory: 'Apanadas',
    nombre: 'Sencilla apanada',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan',
    basePrice: 20000,
    comboPrice: 27000,
    type: 'tradicional',
    image: IMG.hamburguesa3,
  },
  {
    id: 'ham-apanada-especial',
    categoryId: 'hamburguesas',
    subcategory: 'Apanadas',
    nombre: 'Especial apanada',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan',
    basePrice: 21000,
    comboPrice: 28000,
    type: 'tradicional',
    image: IMG.hamburguesa3,
  },
  {
    id: 'ham-apanada-2carnes',
    categoryId: 'hamburguesas',
    subcategory: 'Apanadas',
    nombre: 'Especial apanada 2 carnes',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, champiñones, pollo',
    basePrice: 22000,
    comboPrice: 28500,
    type: 'tradicional',
    image: IMG.hamburguesa3,
  },
  {
    id: 'ham-apanada-tocineta',
    categoryId: 'hamburguesas',
    subcategory: 'Apanadas',
    nombre: 'Especial apanada tocineta',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, pollo, champiñones',
    basePrice: 22000,
    comboPrice: 29000,
    type: 'tradicional',
    image: IMG.hamburguesa3,
  },
  {
    id: 'ham-apanada-mixta',
    categoryId: 'hamburguesas',
    subcategory: 'Apanadas',
    nombre: 'Especial mixta',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, pollo, champiñones, carne de res y de pollo',
    basePrice: 23500,
    comboPrice: 30000,
    type: 'tradicional',
    image: IMG.hamburguesa3,
  },
  {
    id: 'ham-casa-sencilla',
    categoryId: 'hamburguesas',
    subcategory: 'De la casa',
    nombre: 'Sencilla de la casa',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, carne',
    basePrice: 17000,
    comboPrice: 25000,
    type: 'tradicional',
    image: IMG.hamburguesa1,
  },
  {
    id: 'ham-casa-especial',
    categoryId: 'hamburguesas',
    subcategory: 'De la casa',
    nombre: 'Especial de la casa',
    descripcion: 'Tomate, lechuga, cebolla, queso, pan, carne, champiñones, pollo, maíz, chorizo, carne desmechada',
    basePrice: 18000,
    comboPrice: 26000,
    type: 'tradicional',
    image: IMG.hamburguesa1,
  },

  // ── Pastas (mismo precio en lasagna o spaghetti) ────────────────
  {
    id: 'pasta-champinones',
    categoryId: 'pastas',
    nombre: 'Champiñones',
    descripcion:
      'Salsa boloñesa, pasta, champiñones, queso, pan tajado. Disponible en lasagna o spaghetti, mismo precio.',
    basePrice: 19000,
    type: 'tradicional',
    image: IMG.pasta,
    vegetariano: true,
  },
  {
    id: 'pasta-mixta',
    categoryId: 'pastas',
    nombre: 'Mixta',
    descripcion:
      'Salsa boloñesa, pasta, champiñón, pollo, jamón, queso, pan tajado. Disponible en lasagna o spaghetti, mismo precio.',
    basePrice: 21000,
    type: 'tradicional',
    image: IMG.pasta,
  },
  {
    id: 'pasta-pollo',
    categoryId: 'pastas',
    nombre: 'Pollo',
    descripcion: 'Salsa boloñesa, pasta, pollo, queso, pan tajado. Disponible en lasagna o spaghetti, mismo precio.',
    basePrice: 23000,
    type: 'tradicional',
    image: IMG.pasta,
  },
  {
    id: 'pasta-jamon',
    categoryId: 'pastas',
    nombre: 'Jamón',
    descripcion: 'Salsa boloñesa, pasta, jamón, queso, pan tajado. Disponible en lasagna o spaghetti, mismo precio.',
    basePrice: 23500,
    type: 'tradicional',
    image: IMG.pasta,
  },

  // ── Salchipapas & perros calientes ───────────────────────────────
  {
    id: 'salchi-sencilla',
    categoryId: 'calientes',
    subcategory: 'Salchipapas',
    nombre: 'Sencilla',
    descripcion: 'Papa francesa, chorizo, salchicha, queso, salami',
    basePrice: 16000,
    type: 'tradicional',
    image: IMG.salchipapa,
  },
  {
    id: 'salchi-americana',
    categoryId: 'calientes',
    subcategory: 'Salchipapas',
    nombre: 'Americana',
    descripcion: 'Papa francesa, chorizo, salchicha americana, queso, costillas de cerdo',
    basePrice: 17000,
    type: 'tradicional',
    image: IMG.salchipapa,
  },
  {
    id: 'salchi-super-especial',
    categoryId: 'calientes',
    subcategory: 'Salchipapas',
    nombre: 'Súper especial',
    descripcion: 'Papa francesa, chorizo, salchicha americana, champiñón, pollo, queso, costillas de cerdo',
    basePrice: 20000,
    type: 'tradicional',
    image: IMG.salchipapa,
  },
  {
    id: 'perro-sencillo',
    categoryId: 'calientes',
    subcategory: 'Perros calientes',
    nombre: 'Sencillo',
    descripcion: 'Pan, salchicha, queso, salsas, papa en fósforos',
    basePrice: 15500,
    comboPrice: 22000,
    type: 'tradicional',
    image: IMG.perro,
  },
  {
    id: 'perro-americano',
    categoryId: 'calientes',
    subcategory: 'Perros calientes',
    nombre: 'Americano',
    descripcion: 'Pan, salchicha americana, queso, salsas, papa en fósforos, cebolla y piña en trozos',
    basePrice: 16500,
    comboPrice: 24000,
    type: 'tradicional',
    image: IMG.perro,
  },
  {
    id: 'perro-super-especial',
    categoryId: 'calientes',
    subcategory: 'Perros calientes',
    nombre: 'Súper especial',
    descripcion: 'Cebolla, piña en trozos, champiñón y pollo',
    basePrice: 18000,
    comboPrice: 25000,
    type: 'tradicional',
    image: IMG.perro,
  },

  // ── Especiales ────────────────────────────────────────────────────
  {
    id: 'esp-mazorcada',
    categoryId: 'especiales',
    nombre: 'Mazorcada',
    descripcion: 'Champiñones, pollo, carne desmechada, maíz, chorizo, queso + francesa',
    basePrice: 27000,
    type: 'tradicional',
    image: IMG.mazorcada,
  },
  {
    id: 'esp-pechuga-gratinada',
    categoryId: 'especiales',
    nombre: 'Pechuga gratinada',
    descripcion: 'Queso, francesas, ensalada, arepa',
    basePrice: 28000,
    type: 'tradicional',
    image: IMG.pechuga,
  },
  {
    id: 'esp-pechuga-rancho',
    categoryId: 'especiales',
    nombre: 'Pechuga al rancho',
    descripcion: 'Champiñones, pollo, carne desmechada, maíz, chorizo, queso + francesa',
    basePrice: 31000,
    type: 'tradicional',
    image: IMG.pechuga,
  },
  {
    id: 'esp-churrasco',
    categoryId: 'especiales',
    nombre: 'Churrasco',
    descripcion: 'Carne 350 gramos, francesa, ensalada, arepa',
    basePrice: 29000,
    type: 'tradicional',
    image: IMG.churrasco,
  },
  {
    id: 'esp-costillitas-bbq',
    categoryId: 'especiales',
    nombre: 'Costillitas BBQ',
    descripcion: 'Costilla 350 gramos, francesa, ensalada, arepa',
    basePrice: 29000,
    type: 'tradicional',
    image: IMG.churrasco,
  },

  // ── Adicionales (pills sueltos del menú) ────────────────────────
  {
    id: 'add-ingrediente',
    categoryId: 'adicionales',
    nombre: 'Adicionales',
    descripcion: 'Adicional por ingrediente extra',
    basePrice: 3500,
    type: 'entrada',
    image: '',
  },
  {
    id: 'add-francesa',
    categoryId: 'adicionales',
    nombre: 'Porción de francesa',
    descripcion: 'Porción de papa francesa',
    basePrice: 7000,
    type: 'entrada',
    image: '',
  },
  {
    id: 'add-criolla',
    categoryId: 'adicionales',
    nombre: 'Porción de criolla',
    descripcion: 'Porción de papa criolla',
    basePrice: 7000,
    type: 'entrada',
    image: '',
  },

  // ── Bebidas ──────────────────────────────────────────────────────
  {
    id: 'beb-jugo-agua',
    categoryId: 'bebidas',
    subcategory: 'Jugos naturales',
    nombre: 'Jugo natural con agua',
    descripcion: 'Jugo natural preparado con agua',
    basePrice: 6000,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-jugo-leche',
    categoryId: 'bebidas',
    subcategory: 'Jugos naturales',
    nombre: 'Jugo natural con leche',
    descripcion: 'Jugo natural preparado con leche',
    basePrice: 7000,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-agua-pequena',
    categoryId: 'bebidas',
    subcategory: 'Botella de agua',
    nombre: 'Agua pequeña',
    descripcion: 'Botella de agua pequeña',
    basePrice: 2000,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-agua-grande',
    categoryId: 'bebidas',
    subcategory: 'Botella de agua',
    nombre: 'Agua grande',
    descripcion: 'Botella de agua grande',
    basePrice: 3000,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-agua-bretana',
    categoryId: 'bebidas',
    subcategory: 'Botella de agua',
    nombre: 'Agua Bretaña',
    descripcion: 'Botella de agua Bretaña',
    basePrice: 3500,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-cocacola-15l',
    categoryId: 'bebidas',
    subcategory: 'Gaseosas',
    nombre: 'Coca-Cola 1.5L',
    descripcion: 'Gaseosa Coca-Cola 1.5 litros',
    basePrice: 8500,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-postobon-15l',
    categoryId: 'bebidas',
    subcategory: 'Gaseosas',
    nombre: 'Postobón 1.5L',
    descripcion: 'Gaseosa Postobón 1.5 litros',
    basePrice: 7500,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-gaseosa-350',
    categoryId: 'bebidas',
    subcategory: 'Gaseosas',
    nombre: 'Gaseosa 350 ml',
    descripcion: 'Gaseosa personal 350 ml',
    basePrice: 3800,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-gaseosa-500',
    categoryId: 'bebidas',
    subcategory: 'Gaseosas',
    nombre: 'Gaseosa 500 ml',
    descripcion: 'Gaseosa personal 500 ml',
    basePrice: 4000,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-gaseosa-250-vidrio',
    categoryId: 'bebidas',
    subcategory: 'Gaseosas',
    nombre: 'Gaseosa 250 ml (vidrio)',
    descripcion: 'Gaseosa en botella de vidrio 250 ml',
    basePrice: 2800,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
  {
    id: 'beb-gaseosa-250-plastica',
    categoryId: 'bebidas',
    subcategory: 'Gaseosas',
    nombre: 'Gaseosa 250 ml (plástica)',
    descripcion: 'Gaseosa en botella plástica 250 ml',
    basePrice: 2800,
    type: 'bebida',
    image: IMG.bebida,
    vegetariano: true,
  },
];

// Tamaños del menú de pizza (sabores fijos y armador "Crea tu pizza").
// incluidos = # de sabores fijos que trae el tamaño, o # de ingredientes
// libres del armador -- el mismo número cubre ambos casos en esta carta.
export const PIZZA_SIZES = [
  { id: 'small', nombre: 'Small', precio: 30000, incluidos: 1, porciones: 4 },
  { id: 'junior', nombre: 'Junior', precio: 42000, incluidos: 2, porciones: 6 },
  { id: 'mediana', nombre: 'Mediana', precio: 52000, incluidos: 2, porciones: 8 },
  { id: 'familiar', nombre: 'Familiar', precio: 88000, incluidos: 3, porciones: 10 },
];

// Ingredientes del armador "Crea tu pizza" -- precio_extra es el cobro plano
// por ingrediente que exceda los "incluidos" del tamaño elegido ($3.500,
// igual al pill "Adicionales" del menú fijo).
const EXTRA_INGREDIENTE_PRECIO = 3500;
const buildIngredient = (id, nombre, categoria, extra = {}) => ({
  id,
  nombre,
  descripcion: '',
  precio_extra: EXTRA_INGREDIENTE_PRECIO,
  categoria,
  vegetariano: categoria !== 'carne',
  vegano: categoria === 'fruta' || categoria === 'vegetal',
  premium: false,
  dulce: categoria === 'fruta',
  disponible: true,
  defaultIng: false,
  ...extra,
});

export const INGREDIENTS = [
  ...[
    'Jamón',
    'Pollo desmechado',
    'Carne desmechada',
    'Carne molida',
    'Salami',
    'Cabano',
    'Costillas BBQ',
    'Chorizo',
    'Tocineta',
  ].map((nombre) => buildIngredient(`ing-${slug(nombre)}`, nombre, 'carne')),
  ...['Champiñones', 'Cebolla', 'Maíz tierno', 'Tomate', 'Cilantro', 'Espinaca', 'Orégano'].map((nombre) =>
    buildIngredient(`ing-${slug(nombre)}`, nombre, 'vegetal')
  ),
  ...['Piña', 'Cerezas', 'Duraznos', 'Uvas pasas'].map((nombre) =>
    buildIngredient(`ing-${slug(nombre)}`, nombre, 'fruta')
  ),
  ...['Tostacos', 'Queso extra', 'Bocadillo'].map((nombre) => buildIngredient(`ing-${slug(nombre)}`, nombre, 'extra')),
];
